spring.application.name=copa

# Configuração de conexão com o banco que criamos (agora com o comando para criar o banco automaticamente)
spring.datasource.url=jdbc:mysql://localhost:3306/bolao_copa?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=unesc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# O Spring atualiza o banco de dados automaticamente se houver mudanças nas entidades
spring.jpa.hibernate.ddl-auto=update

# Mostra os comandos SQL no console (ótimo para ver o que está acontecendo por trás dos panos)
spring.jpa.show-sql=true